name: flutter_blcs
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 网络请求库
  dio: ^4.0.4
  # RSA加密
  encrypt: ^5.0.1
  # 全局状态管理
  provider: ^6.0.2
  # 持久化操作
  shared_preferences: ^2.0.13
  # 轮播图
  card_swiper : ^2.0.1
  #屏幕适配
  flutter_screenutil: ^5.3.1

#  http: any
#  http_parser: any
#  # 缓存清理
#  path_provider: any
#  # 图片显示，可缓存
#  ok_image: any

#  # 图片拍照
#  image_picker: any
#  # 日期选择
#  flutter_datetime_picker: any
#  # 图形报表
#  flutter_chart_csx: any
#  # UI框架
#  weui: any
#  # 左滑删除
#  left_scroll_actions: any
#  # 推送
#  jpush_flutter: any
#  # 图片压缩
#  flutter_luban: any
#  # 全局状态管理
#  provider: any

#  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
#  # 支持自动化json
#  json_serializable: ^6.1.4
#  json_annotation: ^4.4.0
#  build_runner: ^2.1.7
#  json_model: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - images/ic_coffee.png
     - images/ic_avator.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

