name: flutter_blcs
description: A new Flutter application.

#publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # 网络请求库
  dio: ^4.0.4
  # RSA加密
  encrypt: ^5.0.1
  # 全局状态管理
  provider: ^6.0.2
  # 持久化操作
  shared_preferences: ^2.0.13
  # 轮播图
  card_swiper : ^2.0.1
  #屏幕适配
  flutter_screenutil: ^5.3.1
  #代码高亮
  flutter_syntax_view: ^4.0.0
  # log打印
  logger: ^1.1.0
  # 动画插件
  flare_flutter: ^3.0.2
  # 字体
  google_fonts: ^2.3.1
  # 自定义动画
  simple_animations: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  # UME  应用内调试工具
  flutter_ume: ^0.3.0+1
  flutter_ume_kit_ui: ^0.3.0+1
  flutter_ume_kit_device: ^0.3.0
  flutter_ume_kit_perf: ^0.3.0
  flutter_ume_kit_show_code: ^0.3.0
  flutter_ume_kit_console: ^0.3.0
  flutter_ume_kit_dio: ^0.3.0

#  # 支持自动化json
#  json_serializable: ^6.1.4
#  json_annotation: ^4.4.0
#  build_runner: ^2.1.7
#  json_model: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - static/images/
     - static/assets/
     - static/jsons/
#  fonts:
#    - family: wxcIconFont
#      fonts:
#        - asset: static/font/iconfont.ttf
#    - family: google_kavivanar
#      fonts:
#        - asset: static/font/google_kavivanar.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
